   187.9ms (setup:858): 2025-04-16 22:03:20
   188.3ms (setup:859): /usr/bin/pipx install pygame
   188.4ms (setup:860): pipx version is 1.4.3
   188.4ms (setup:861): Default python interpreter is '/usr/bin/python3'
   188.4ms (mkdir:74): creating directory /home/bibisam06/.local/share/pipx/venvs
   189.0ms (mkdir:74): creating directory /home/bibisam06/.local/bin
   189.1ms (mkdir:74): creating directory /home/bibisam06/.local/share/man
   189.5ms (mkdir:74): creating directory /home/bibisam06/.cache/pipx
   190.2ms (setup:870): Adding CACHEDIR.TAG to cache directory
   190.9ms (package_name_from_spec:370): Determined package name: pygame
   191.3ms (package_name_from_spec:371): Package name determined in 0.0s
   191.9ms (run_subprocess:168): running /usr/bin/python3 -m venv --without-pip /home/bibisam06/.local/share/pipx/venvs/pygame
   240.8ms (run_subprocess:190): stdout:
   240.9ms (run_subprocess:192): stderr:
   240.9ms (run_subprocess:193): returncode: 0
   241.7ms (run_subprocess:168): running /usr/bin/python3 -m venv --clear /home/bibisam06/.local/share/pipx/shared
  2908.6ms (run_subprocess:190): stdout:
  2908.7ms (run_subprocess:192): stderr:
  2908.7ms (run_subprocess:193): returncode: 0
  2909.0ms (run_subprocess:168): running <checking pip's availability>
  2925.9ms (run_subprocess:190): stdout: ModuleSpec(name='pip', loader=<_frozen_importlib_external.SourceFileLoader object at 0x7fecef847ce0>, origin='/home/bibisam06/.local/share/pipx/shared/lib/python3.12/site-packages/pip/__init__.py', submodule_search_locations=['/home/bibisam06/.local/share/pipx/shared/lib/python3.12/site-packages/pip'])
  2926.0ms (run_subprocess:193): returncode: 0
  2926.1ms (upgrade:98): Upgrading shared libraries in /home/bibisam06/.local/share/pipx/shared
  2926.6ms (run_subprocess:168): running /home/bibisam06/.local/share/pipx/shared/bin/python -m pip --no-input --disable-pip-version-check install --force-reinstall -q --upgrade pip >= 23.1
  6886.1ms (run_subprocess:190): stdout:
  6886.2ms (run_subprocess:192): stderr: ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    unknown package:
        Expected sha256 c46efd13b6aa8279f33f2864459c8ce587ea6a1a59ee20de055868d8f7688f7f
             Got        c10552054be99b0cd6051c3ed295cbccc42f56b722abc8af0aacb19c6d405b0f
  6886.2ms (run_subprocess:193): returncode: 1
  6886.5ms (upgrade:125): Failed to upgrade shared libraries
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pipx/shared_libs.py", line 119, in upgrade
    subprocess_post_check(upgrade_process)
  File "/usr/lib/python3/dist-packages/pipx/util.py", line 205, in subprocess_post_check
    raise PipxError(f"{' '.join([str(x) for x in completed_process.args])!r} failed")
pipx.util.PipxError: '/home/bibisam06/.local/share/pipx/shared/bin/python -m pip --no-input --disable-pip-version-check install --force-reinstall -q --upgrade pip >= 23.1' failed
  6899.2ms (run_subprocess:168): running /home/bibisam06/.local/share/pipx/venvs/pygame/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
  6915.6ms (run_subprocess:190): stdout: /home/bibisam06/.local/share/pipx/venvs/pygame/lib/python3.12/site-packages
  6915.7ms (run_subprocess:193): returncode: 0
  6915.9ms (run_subprocess:168): running /home/bibisam06/.local/share/pipx/shared/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
  6931.0ms (run_subprocess:190): stdout: /home/bibisam06/.local/share/pipx/shared/lib/python3.12/site-packages
  6931.0ms (run_subprocess:193): returncode: 0
  6931.2ms (run_subprocess:168): running /home/bibisam06/.local/share/pipx/venvs/pygame/bin/python --version
  6932.6ms (run_subprocess:190): stdout: Python 3.12.3
  6932.7ms (run_subprocess:192): stderr:
  6932.7ms (run_subprocess:193): returncode: 0
  6932.9ms (_parsed_package_to_package_or_url:137): cleaned package spec: pygame
  6933.5ms (run_subprocess:168): running /home/bibisam06/.local/share/pipx/venvs/pygame/bin/python -m pip --no-input install pygame
315936.4ms (run_subprocess:193): returncode: 0
315955.8ms (run_subprocess:168): running <fetch_info_in_venv commands>
316040.3ms (run_subprocess:190): stdout: {"sys_path": ["/usr/lib/python312.zip", "/usr/lib/python3.12", "/usr/lib/python3.12/lib-dynload", "/home/bibisam06/.local/share/pipx/venvs/pygame/lib/python3.12/site-packages", "/home/bibisam06/.local/share/pipx/shared/lib/python3.12/site-packages"], "python_version": "3.12.3", "environment": {"implementation_name": "cpython", "implementation_version": "3.12.3", "os_name": "posix", "platform_machine": "x86_64", "platform_release": "5.15.167.4-microsoft-standard-WSL2", "platform_system": "Linux", "platform_version": "#1 SMP Tue Nov 5 00:21:55 UTC 2024", "python_full_version": "3.12.3", "platform_python_implementation": "CPython", "python_version": "3.12", "sys_platform": "linux"}}
316040.4ms (run_subprocess:193): returncode: 0
316102.9ms (get_venv_metadata_for_package:339): get_venv_metadata_for_package: 149ms
316103.3ms (_parsed_package_to_package_or_url:137): cleaned package spec: pygame
316104.8ms (rmdir:55): removing directory /home/bibisam06/.local/share/pipx/venvs/pygame
316135.9ms (cli:924): PipxError: No apps associated with package pygame or its dependencies. If you are attempting to install a library, pipx should not be used. Consider using pip or a similar tool instead.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pipx/main.py", line 921, in cli
    return run_pipx_command(parsed_pipx_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pipx/main.py", line 219, in run_pipx_command
    return commands.install(
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pipx/commands/install.py", line 100, in install
    run_post_install_actions(
  File "/usr/lib/python3/dist-packages/pipx/commands/common.py", line 410, in run_post_install_actions
    raise PipxError(
pipx.util.PipxError: No apps associated with package pygame or its dependencies. If you are attempting to install a library, pipx should not be used. Consider using pip or a similar tool instead.
316144.2ms (cli:932): pipx finished.
